name: "Put milestones on autopilot"
on:
  schedule:
  - cron: "0 * * * *"
  push:
    branches:
      - master
    paths:
      - .github/workflows/milestones.yml

jobs:
  milestones:
    runs-on: ubuntu-latest
    steps:
    - uses: instantish/memorable-milestones@1.1.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
